num1,num2=map(int,input().split())
operator=input().strip()
if(operator=='+'):
  print(a+b)
elif(operator=='-'):
  print(a-b)
elif(operator=='*'):
  print(a*b)
elif(operator=='/'):
  print(a/b)
elif(operator=='%'):
  print(a%b)
elif(operator=='&'):
  print(a&b)
elif(operator=='^'):
  print(a^b)
elif(operator=='**'):
  print(a**b)
elif(operator=='|'):
  print(a|b)
